name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version-file: package.json
    - name: npm ci, lint, build, and test
      run: |
        npm ci
        npm run lint
        npm run build
        npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: io.github.ssmendon.obsidian-filename-plugin
        path: |
          ./dist/*.js
          ./dist/*.json
        retention-days: 5
