name: Node.js CI

on:
  push:
    paths:
    - '.github/**'
    - '**.cjs'
    - '**.js'
    - '**.json'
    - '**.mjs'
    - '**.ts'
    - 'obsidian/**'
    - 'src/**'
    - 'test/**'

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
